### ISSUE TITLE
[SDK] Tracking all RPC methods

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#681]
### What We Currently Track
We track the following events within the MetaMask SDK:

- sdk_connect_request_started: Initiation of a connection request from a dapp.
- sdk_connect_request_started_mobile: Initiation of a connection request from a mobile device when the dapp platform is not available.
- sdk_reconnect_request_started: Attempt to resume a connection on an existing room id by a dapp.
- sdk_connection_established: Successful connection establishment after key exchange.
- sdk_connection_established_mobile: Successful mobile connection establishment after key exchange when the dapp platform is available.
- sdk_connection_authorized: Connection authorised by mobile.
- sdk_connection_rejected: Connection rejected by mobile.
- sdk_disconnected: Disconnection event on mobile.
- sdk_use_extension: User opts for the Extension on the connection modal.
- sdk_use_inapp_browser: SDK used within the in-app browser.
- sdk_extension_utilized: SDK persisting user’s extension selection. 

We track the following event properties on the MetaMask mobile app: 

- request_source: The source of the dapp connection (In-app browser, WalletConnect, SDK)
- request_platform: The platform of the dapp connecting to MetaMask mobile app via SDK. 

Events are fired within the SDK and transmitted to our servers, where they are fed into a NodeJS segment source. We use Segment to map these events into Mixpanel, allowing us to visualise and analyse the data. This process helps us answer key questions about SDK usage, such as the number of connections and mobile events via SDK connections.

### Which Problems Can SDK Data Tracking Plan Solve? 
How do dapps use the MetaMask SDK? 
How does SDK perform after establishing connection between the dapp and the mobile app?  
What is the value that SDK brings? How many new users/daily active users does SDK bring to the mobile app? 

### TASK: Tracking RPC Methods Called on the SDK
We can track RPC calls only if the developer uses read-only calls via Infura API. We cannot track every RPC method that the developer is using. 
The main goals for tracking RPC methods are:

- To analyse how dapps are using the MetaMask SDK.
- To determine the number of RPC calls made through the SDK.
- To assess the success rate of these RPC calls in reaching the MetaMask mobile app.

### What Data We Can Track
We can track the following RPC method events within the MetaMask SDK:
RPC Method Calls: ONLY the RPC method invoked by a dapp through the SDK that require wallet confirmation (check the google sheet).
Success Events: RPC calls that successfully reach the MetaMask mobile app.
Failure Events: RPC calls that fail to reach the MetaMask mobile app.
Dapp metadata with each RPC method that we track should also be tracked. 

### RPC Methods to track: 
https://docs.google.com/spreadsheets/d/1zsgSOSYtPnvy-EOLycVYptSU7SluphXycgEgQFCNYgk/edit#gid=0

### SDK Events to Generate: 
sdk_rpc_request { method: "rpc_name", provider: "mobile" | "extension" } (fired from the dapp side from the SDK)
sdk_rpc_received { method: "rpc_name", ...dappMetadata }  (fired from the mobile app side, including all dappMetadata from the connection receiving the message)
sdk_rpc_result ( success: boolean, ...dappMetadata ) (fired from the mobile side )

### Acceptance Criteria: 

- [ ] We should generate 3 new events 
- sdk_rpc_request (fired from the dapp side from the SDK)
- sdk_rpc_received (fired from the mobile app side)
- sdk_rpc_result (fired from the mobile side)
- [ ] All 3 events should contain under event "properties" 
  - [ ] channel id (in our SDK user_id)
  - [ ] dapp metadata properties (title, url, platform, sdkversion, source) for mapping
  - [ ] RPC Method name
- [ ] These events should be tracked on
  - [ ] mobile to mobile connections
  - [ ] desktop to mobile connections
  - [ ] desktop to extention connections
- [ ] unit tests on both client and mobile to validate events are triggered upon emitting rpc method
