### ISSUE TITLE
Integrate SDK into eth_phishing_detection with permission systems

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#696]
### Description: 
eth_phishing_detection is a utility for detecting phishing domains targeting Web3 users.
For checking why a given domain was blocked, there is a third-party [search tool](https://app.chainpatrol.io/search) maintained by ChainPatrol.

### User Story
When user connects to a dapp  via SDK that's url is blacklisted in our eth_phishing_detection list, MetaMask mobile app should show a warning to the user before selecting to connect or not. This will allow MetaMask to warn the user while letting user to decide what to do next.

### Task
1. See initial implementation from https://github.com/MetaMask/metamask-mobile/pull/7491 which seems to be deprecated since it now uses a full screen red window modal.
Testing steps:
- open one of the blacklisted url in inapp browser to trigger the fishing warning modal
- url to check for example: `cyxw.btbethp.cc`
2. Recreate pishing detection in AccountConnect.tsx

<img width="421" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU4rQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4aaaeab12dcdbebd5d253eb3fe3215005c9b5238/image.png" alt="image.png" />

<img width="368" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTErQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--366a795369530acab2672cc7b52011a3195f9091/image.png" alt="image.png" />

## Acceptance Criteria
 - [ ] Scenario: Integrate SDK into eth_phishing_detection with permission systems**
 - [x] Given the user connects to a dapp via SDK with a URL that is blacklisted in eth_phishing_detection
 - [x] When the user is prompted with a warning to connect or not
 - [x] Then the warning should be displayed before the user selects to connect or not
 - [ ] The warning should be displayed in the permission systems connect flow
 - [ ] Unit tests should be created to validate the UI flow
 - [ ] QA validation is required
 - [ ] It should work the same way for JS, iOS, Android, Unity SDKs

**Comment by omridan159** [comment]
Added here:
https://github.com/MetaMask/metamask-mobile/pull/8920
