### ISSUE TITLE
[JS] Add sdk_rpc event to JS SDK when dapp triggers an RPC method

### ISSUE THREAD

**Issue by ezgi-cengiz** [MetaMask/metamask-sdk#736]
### Task

1. Add the following events to the JS SDK
sdk_rpc
2. sdk_rpc should be fired when dapp calls an RPC 
3. Both events should contain under "properties":
- rpc method name
- dapp metadata(title, url, source, sdkversion, platform, channel id(user id), timestamp)

### Acceptance Criteria
- [ ] Events should be added and fired correctly
- [ ] Events have the right format and should have additional info under "properties" for the correct mixpanel mapping.
- [ ] Unit tests should be added on the mobile app to check whether they are triggered correctly.
- [ ] QA should be done with Segment and Mixpanel to confirm if the events are fired correctly, received correctly on segment and mapped correctly on mixpanel
